(()=>{
  'use strict';
  const VERSION='1';
  const page=(location.pathname.split('/').pop()||'index.html').toLowerCase();
  let managementDemo;
  function ensureManagementDemo(){
    if(managementDemo)return managementDemo;
    managementDemo=document.createElement('div');
    managementDemo.className='gestor-management-demo';
    managementDemo.hidden=true;
    managementDemo.innerHTML=`<section class="gestor-demo-screen gestor-demo-justifications" hidden>
      <header class="gestor-demo-topbar"><span class="gestor-demo-back">←</span><div><small>GESTÃO 360°</small><h2>Validação de justificativas</h2></div><button disabled>↻ Atualizar</button></header>
      <div class="gestor-demo-period"><strong>Período</strong><span>Mês atual</span><span>Ano atual</span></div>
      <div class="gestor-demo-kpis"><article class="is-active"><small>AGUARDANDO VALIDAÇÃO</small><strong>3</strong><span>ainda não regularizam a meta</span></article><article><small>APROVADAS</small><strong>1</strong><span>crédito aplicado à meta</span></article><article><small>REJEITADAS</small><strong>1</strong><span>escola permanece na prioridade</span></article></div>
      <div class="gestor-demo-panel"><header><div><h3>Justificativas registradas</h3><p>Confira a escola, o período e o motivo antes de decidir.</p></div><span class="gestor-demo-search">⌕ Escola, supervisor ou motivo...</span></header><div class="gestor-demo-filters"><b>Pendentes</b><span>Todas</span><span>Aprovadas</span><span>Rejeitadas</span></div><div class="gestor-demo-row"><div><strong>Escola de demonstração</strong><small>Supervisor responsável</small></div><div><small>REFERÊNCIA DA META</small><strong>Mês atual · 1 crédito</strong></div><div class="gestor-demo-reason"><small>MOTIVO INFORMADO</small><strong>Justificativa apresentada pelo supervisor</strong></div><div class="gestor-demo-decisions"><em>AGUARDANDO</em><span><button disabled>✓ Aprovar</button><button disabled>× Rejeitar</button></span></div></div></div>
    </section>
    <section class="gestor-demo-screen gestor-demo-priority" hidden>
      <header class="gestor-demo-topbar"><span class="gestor-demo-back">←</span><div><small>GESTÃO 360°</small><h2>Prioridades de acompanhamento</h2></div><span><button disabled>↻ Atualizar</button><button disabled>↓ Extrair CSV</button></span></header>
      <div class="gestor-demo-rule"><b>15</b><span><strong>Regra inteligente de acompanhamento</strong><small>Identifica escolas abaixo da meta, sem visita recente ou com validações pendentes.</small></span></div>
      <div class="gestor-demo-kpis gestor-demo-priority-kpis"><article class="is-active"><small>PRIORIDADES CRÍTICAS</small><strong>54</strong><span>abaixo da meta e sem justificativa</span></article><article><small>SEM VISITA +15 DIAS</small><strong>51</strong><span>inclui escolas nunca visitadas</span></article><article><small>AGUARDANDO VALIDAÇÃO</small><strong>3</strong><span>registros pendentes ou em análise</span></article><article><small>DENTRO DA REGRA</small><strong>2</strong><span>meta ou justificativa regular</span></article></div>
      <div class="gestor-demo-panel gestor-demo-priority-table"><header><div><h3>Escolas que exigem atenção</h3><p>Use a pesquisa e as classificações para investigar o cenário.</p></div><span class="gestor-demo-search">⌕ Pesquisar escola ou classificação...</span></header><div class="gestor-demo-filters"><b>Todas</b><span>Meta não atingida</span><span>Sem visita +15 dias</span><span>Aguardando validação</span><span>Justificadas</span></div><div class="gestor-demo-table-head"><span>ESCOLA</span><span>ÚLTIMA VISITA</span><span>REALIZADAS</span><span>META</span><span>CLASSIFICAÇÃO</span></div><div class="gestor-demo-table-row"><strong>Escola de demonstração</strong><span>Nunca visitada</span><span>0</span><span>2</span><span><em>Meta não atingida</em> <em>Sem visita +15 dias</em></span></div></div>
    </section>`;
    document.body.appendChild(managementDemo);
    return managementDemo;
  }
  function showManagementDemo(name){ensureManagementDemo();managementDemo.hidden=false;managementDemo.querySelectorAll('.gestor-demo-screen').forEach(screen=>screen.hidden=!screen.classList.contains(`gestor-demo-${name}`))}
  function showJustificationDemo(){showManagementDemo('justifications')}
  function showPriorityDemo(){showManagementDemo('priority')}
  function hideManagementDemo(){if(managementDemo)managementDemo.hidden=true}
  const configs={
    'index.html':[
      {selector:'#loginScreen',title:'Acesso ao Gestor-ESE',text:'Entre usando o identificador administrativo fornecido pela gestão e sua senha.'},
      {selector:'#loginEmail',title:'Usuário administrativo',text:'Digite somente o usuário recebido, por exemplo admteste. Não é necessário informar o endereço de e-mail completo.'},
      {selector:'#loginPassword',title:'Senha',text:'Informe sua senha com atenção. Por segurança, ela não é exibida na tela.'},
      {selector:'#btnEmailLogin',title:'Entrar no sistema',text:'Depois de preencher os campos, use este botão para validar o acesso ao portal.'},
      {selector:'.ure-sidebar',title:'Menu principal',text:'O menu organiza a Visão geral, os cadastros e os módulos de gestão. Ele também pode ser recolhido para ampliar a área de trabalho.'},
      {selector:'.ure-nav',title:'Navegação do portal',text:'Use estes atalhos para acessar cadastros, metas, correções de status, localização das escolas e a Equipe ESE.'},
      {selector:'#openAdministratorRegistry',title:'Administradores',text:'Somente o administrador master visualiza esta opção e pode preparar novos acessos administrativos.',tip:'Outros administradores não podem cadastrar administradores nem supervisores.'},
      {selector:'#openSupervisorRegistry',title:'Supervisores',text:'O administrador master prepara supervisores, vincula o perfil ao acesso e organiza as escolas acompanhadas.'},
      {selector:'#openSchoolRegistry',title:'Cadastro de escolas',text:'Cadastre escolas e gerencie os vínculos com um ou mais supervisores sem substituir vínculos existentes.'},
      {selector:'.ure-user',title:'Conta conectada',text:'Confira o nome e o perfil atual. O ícone de saída encerra o acesso com segurança.',tip:'Sempre saia do portal ao terminar o trabalho em computadores compartilhados.'},
      {selector:'.ure-topbar',title:'Visão geral',text:'Esta é a página inicial da gestão. Aqui você acompanha os principais números e acessa rapidamente todas as análises.'},
      {selector:'#searchOpenButton',title:'Busca em tempo real',text:'Pesquise registros por supervisor, escola, status, ação ou autor. A consulta também pode ser aberta com Ctrl + K.'},
      {selector:'.ure-hero-actions',title:'Panorama e histórico',text:'Abra o panorama mensal para uma leitura consolidada ou o Histórico para consultar acontecimentos por data, supervisor e escola.'},
      {selector:'.ure-orbit',title:'Resumo do período',text:'Este painel apresenta escolas conectadas, visitas do dia e volume realizado no mês diretamente a partir da base.'},
      {selector:'.ure-module-grid',title:'Módulos de análise',text:'Acesse planejamento por supervisor, planejamento por escola, metas e filtros detalhados.'},
      {selector:'#themePickerButton',title:'Personalizar cores',text:'Escolha uma paleta mais confortável para leitura. A preferência fica memorizada neste navegador.'},
      {selector:'.ure-pulse',title:'Atividade das últimas semanas',text:'O gráfico mostra o volume diário de eventos das duas últimas semanas, com total, média e dias de maior movimento.'},
      {selector:'.ure-focus',title:'Prioridades de acompanhamento',text:'Veja escolas com meta não atingida, sem visita há mais de 15 dias, justificadas e registros aguardando validação.'},
      {selector:'.ure-validation-action',title:'Validar justificativas',text:'Este atalho abre a análise das justificativas enviadas. A gestão pode aprovar ou rejeitar cada solicitação.'},
      {selector:'.gestor-demo-justifications .gestor-demo-topbar',prepare:showJustificationDemo,title:'Tela de validação',text:'Aqui a gestão acompanha as justificativas pendentes, aprovadas e rejeitadas no período. Esta tela do Tour é apenas demonstrativa.'},
      {selector:'.gestor-demo-justifications .gestor-demo-kpis',prepare:showJustificationDemo,title:'Situação das justificativas',text:'Os indicadores mostram quantas justificativas aguardam decisão e quantas já foram aprovadas ou rejeitadas.'},
      {selector:'.gestor-demo-justifications .gestor-demo-row',prepare:showJustificationDemo,title:'Analisar antes de decidir',text:'Confira escola, supervisor, referência da meta e motivo informado. Depois, no sistema real, escolha Aprovar ou Rejeitar.',tip:'A aprovação concede o crédito previsto à meta; a rejeição mantém a escola na prioridade.'},
      {selector:'.ure-focus > button',prepare:hideManagementDemo,title:'Ver prioridades',text:'Este botão abre a relação completa das escolas que exigem atenção.'},
      {selector:'.gestor-demo-priority .gestor-demo-topbar',prepare:showPriorityDemo,title:'Tela de prioridades',text:'A página consolida as escolas que precisam de acompanhamento e permite atualizar ou extrair a relação em CSV.'},
      {selector:'.gestor-demo-rule',prepare:showPriorityDemo,title:'Regra de acompanhamento',text:'A regra explica por que uma escola entra na lista: meta não atingida, visita atrasada, justificativa ou validação pendente.'},
      {selector:'.gestor-demo-priority-kpis',prepare:showPriorityDemo,title:'Leitura do cenário',text:'Compare prioridades críticas, escolas sem visita há mais de 15 dias, validações aguardando análise e escolas dentro da regra.'},
      {selector:'.gestor-demo-priority-table',prepare:showPriorityDemo,title:'Investigar as escolas',text:'Pesquise uma escola ou use os filtros de classificação para entender o motivo da prioridade e acompanhar sua situação.'}
    ]
  };
  let steps=[],index=0,active=false,shades=[],focus,tooltip;
  const icon='<svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.4 2.2c-.8.4-1.2.9-1.2 1.8M12 17h.01"/></svg>';
  const visible=el=>el&&!el.hidden&&el.getClientRects().length>0;
  const currentSteps=()=> (configs[page]||[]).map(item=>({...item,element:document.querySelector(item.selector)})).filter(item=>item.element&&(item.prepare||visible(item.element)));
  const userKey=()=>document.getElementById('userName')?.textContent?.trim()||'administrador';
  const storageKey=()=>`gestor-ese-tour:${userKey()}:v${VERSION}`;
  function removeTour(){shades.forEach(el=>el.remove());shades=[];focus?.remove();tooltip?.remove();focus=tooltip=null;active=false;document.removeEventListener('keydown',onKey);hideManagementDemo()}
  function close(completed=false){if(completed){try{localStorage.setItem(storageKey(),'completed')}catch(_){}}removeTour()}
  function onKey(event){if(event.key==='Escape')close();if(event.key==='ArrowRight'){event.preventDefault();next()}if(event.key==='ArrowLeft'){event.preventDefault();previous()}}
  function ensureLayer(){if(shades.length)return;shades=Array.from({length:4},()=>{const el=document.createElement('div');el.className='gestor-tour-shade';document.body.appendChild(el);return el});focus=document.createElement('div');focus.className='gestor-tour-focus';document.body.appendChild(focus);tooltip=document.createElement('section');tooltip.className='gestor-tour-tooltip';tooltip.setAttribute('role','dialog');tooltip.setAttribute('aria-modal','true');document.body.appendChild(tooltip)}
  function position(){if(!active||!steps[index])return;const rect=steps[index].element.getBoundingClientRect(),pad=7,w=innerWidth,h=innerHeight,left=Math.max(0,rect.left-pad),top=Math.max(0,rect.top-pad),right=Math.min(w,rect.right+pad),bottom=Math.min(h,rect.bottom+pad);Object.assign(shades[0].style,{left:'0',top:'0',width:'100%',height:`${top}px`});Object.assign(shades[1].style,{left:'0',top:`${top}px`,width:`${left}px`,height:`${bottom-top}px`});Object.assign(shades[2].style,{left:`${right}px`,top:`${top}px`,width:`${w-right}px`,height:`${bottom-top}px`});Object.assign(shades[3].style,{left:'0',top:`${bottom}px`,width:'100%',height:`${h-bottom}px`});Object.assign(focus.style,{left:`${left}px`,top:`${top}px`,width:`${Math.max(0,right-left)}px`,height:`${Math.max(0,bottom-top)}px`});const tipRect=tooltip.getBoundingClientRect(),spaceBelow=h-bottom,tipTop=spaceBelow>tipRect.height+18?bottom+12:Math.max(12,top-tipRect.height-12),tipLeft=Math.min(Math.max(12,left),w-tipRect.width-12);Object.assign(tooltip.style,{left:`${tipLeft}px`,top:`${tipTop}px`})}
  function render(){const step=steps[index];if(!step)return;step.prepare?.();step.element.scrollIntoView({behavior:'smooth',block:'center',inline:'nearest'});tooltip.innerHTML=`<button class="gestor-tour-close" type="button" aria-label="Fechar guia">×</button><p class="kicker">Manual interativo</p><h2>${step.title}</h2><p>${step.text}</p>${step.tip?`<p class="tip">${step.tip}</p>`:''}<div class="gestor-tour-actions"><span class="gestor-tour-count">${index+1} de ${steps.length}</span><button class="gestor-tour-nav" data-action="previous" type="button" ${index===0?'disabled':''}>Anterior</button><button class="gestor-tour-nav primary" data-action="next" type="button">${index===steps.length-1?'Concluir':'Próximo'}</button></div>`;tooltip.querySelector('.gestor-tour-close').onclick=()=>close();tooltip.querySelector('[data-action="previous"]').onclick=previous;tooltip.querySelector('[data-action="next"]').onclick=next;setTimeout(position,260)}
  function start(){removeTour();if(page==='index.html')ensureManagementDemo();steps=currentSteps();if(!steps.length)return;active=true;index=0;ensureLayer();document.addEventListener('keydown',onKey);render()}
  function next(){if(index>=steps.length-1){close(true);return}index++;render()}
  function previous(){if(index>0){index--;render()}}
  function showWelcome(){if(document.querySelector('.gestor-welcome-backdrop'))return;const layer=document.createElement('div');layer.className='gestor-welcome-backdrop';layer.innerHTML='<section class="gestor-welcome" role="dialog" aria-modal="true" aria-labelledby="gestorWelcomeTitle"><div class="gestor-welcome-icon">?</div><p class="kicker">Bem-vindo ao Gestor-ESE</p><h2 id="gestorWelcomeTitle">Deseja conhecer o portal?</h2><p>Preparamos um guia rápido para apresentar os cadastros, indicadores e ferramentas de acompanhamento. Você pode iniciar agora ou acessar novamente pelo botão <strong>Ajuda / Tour</strong>.</p><div class="gestor-welcome-actions"><button type="button" data-choice="later">Fazer depois</button><button class="primary" type="button" data-choice="start">Iniciar tour</button></div></section>';document.body.appendChild(layer);layer.querySelector('[data-choice="later"]').onclick=()=>{try{localStorage.setItem(storageKey(),'later')}catch(_){}layer.remove()};layer.querySelector('[data-choice="start"]').onclick=()=>{layer.remove();start()}}
  function offerFirstTour(){if(page!=='index.html'||visible(document.querySelector('#loginScreen'))||!visible(document.querySelector('#homeView')))return;try{if(localStorage.getItem(storageKey()))return}catch(_){}showWelcome()}
  function mount(){if(!(configs[page]||[]).length)return;const help=document.createElement('button');help.type='button';help.className='gestor-help-button';help.innerHTML=`${icon}<span>Ajuda / Tour</span>`;help.setAttribute('aria-haspopup','menu');const menu=document.createElement('div');menu.className='gestor-tour-menu';menu.hidden=true;menu.innerHTML='<strong>Manual interativo</strong><button type="button">Iniciar guia desta tela</button>';document.body.append(menu,help);help.onclick=()=>{menu.hidden=!menu.hidden};menu.querySelector('button').onclick=()=>{menu.hidden=true;start()};document.addEventListener('click',event=>{if(!menu.hidden&&!menu.contains(event.target)&&!help.contains(event.target))menu.hidden=true});addEventListener('resize',position,{passive:true});addEventListener('scroll',position,{passive:true});new MutationObserver(offerFirstTour).observe(document.body,{subtree:true,attributes:true,attributeFilter:['hidden'],childList:true,characterData:true});offerFirstTour()}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
  window.GestorESETour={start,close};
})();
